//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.HomeCare.Resources
{
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages
    {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() { }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(
                        "Shared.HomeCare.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        //  Generic CRUD / Operation Results 

        /// <summary>{0} added successfully.</summary>
        public static string AddedSuccessfully => ResourceManager.GetString("AddedSuccessfully", resourceCulture);
        /// <summary>{0} removed successfully.</summary>
        public static string RemovedSuccessfully => ResourceManager.GetString("RemovedSuccessfully", resourceCulture);
        /// <summary>{0} created successfully.</summary>
        public static string CreatedSuccessfully => ResourceManager.GetString("CreatedSuccessfully", resourceCulture);
        /// <summary>{0} updated successfully.</summary>
        public static string UpdatedSuccessfully => ResourceManager.GetString("UpdatedSuccessfully", resourceCulture);
        /// <summary>{0} deleted successfully.</summary>
        public static string DeletedSuccessfully => ResourceManager.GetString("DeletedSuccessfully", resourceCulture);
        /// <summary>{0} retrieved successfully.</summary>
        public static string GetSuccessfully => ResourceManager.GetString("GetSuccessfully", resourceCulture);
        /// <summary>Operation completed successfully.</summary>
        public static string SuccessResponse => ResourceManager.GetString("SuccessResponse", resourceCulture);
        /// <summary>An unexpected error occurred. Please try again.</summary>
        public static string FailedResponse => ResourceManager.GetString("FailedResponse", resourceCulture);
        /// <summary>Invalid requested data.</summary>
        public static string InvalidRequest => ResourceManager.GetString("InvalidRequest", resourceCulture);
        /// <summary>{0} not found.</summary>
        public static string NotFound => ResourceManager.GetString("NotFound", resourceCulture);
        /// <summary>A {0} with this property already exists.</summary>
        public static string DuplicateRecord => ResourceManager.GetString("DuplicateRecord", resourceCulture);
        /// <summary>{0} has no image on record.</summary>
        public static string NoImage => ResourceManager.GetString("NoImage", resourceCulture);

        //  Generic Validation 

        /// <summary>{0} is required.</summary>
        public static string Required => ResourceManager.GetString("Required", resourceCulture);
        /// <summary>At least one of the following fields is required: {0}.</summary>
        public static string AtLeastOneFieldRequired => ResourceManager.GetString("AtLeastOneFieldRequired", resourceCulture);
        /// <summary>{0} must be at least {1} characters.</summary>
        public static string MinLength => ResourceManager.GetString("MinLength", resourceCulture);
        /// <summary>{0} must not exceed {1} characters.</summary>
        public static string MaxLength => ResourceManager.GetString("MaxLength", resourceCulture);
        /// <summary>Name cannot exceed 150 characters.</summary>
        public static string NameMaxLength => ResourceManager.GetString("NameMaxLength", resourceCulture);
        /// <summary>{0} must be greater than 0.</summary>
        public static string GreaterThanZero => ResourceManager.GetString("GreaterThanZero", resourceCulture);
        /// <summary>{0} must be between 1 and 99.</summary>
        public static string RangeBetween => ResourceManager.GetString("RangeBetween", resourceCulture);
        /// <summary>{0} range is invalid. Min must be less than or equal to Max.</summary>
        public static string RangeInvalid => ResourceManager.GetString("RangeInvalid", resourceCulture);

        //  Auth / Token 

        /// <summary>Invalid email or password.</summary>
        public static string InvalidCredentials => ResourceManager.GetString("InvalidCredentials", resourceCulture);
        /// <summary>Account is inactive.</summary>
        public static string AccountInactive => ResourceManager.GetString("AccountInactive", resourceCulture);
        /// <summary>Logged out successfully.</summary>
        public static string LoggedOut => ResourceManager.GetString("LoggedOut", resourceCulture);
        /// <summary>Token refreshed successfully.</summary>
        public static string TokenRefreshedSuccessfully => ResourceManager.GetString("TokenRefreshedSuccessfully", resourceCulture);
        /// <summary>Refresh token is missing.</summary>
        public static string RefreshTokenMissing => ResourceManager.GetString("RefreshTokenMissing", resourceCulture);
        /// <summary>Invalid or expired refresh token.</summary>
        public static string RefreshTokenInvalid => ResourceManager.GetString("RefreshTokenInvalid", resourceCulture);
        /// <summary>Invalid or expired refresh token. Please login again.</summary>
        public static string InvalidOrExpiredRefreshToken => ResourceManager.GetString("InvalidOrExpiredRefreshToken", resourceCulture);

        //  Password Reset 

        /// <summary>Invalid or expired reset link.</summary>
        public static string ResetLinkInvalid => ResourceManager.GetString("ResetLinkInvalid", resourceCulture);
        /// <summary>This reset link has already been used.</summary>
        public static string ResetLinkUsed => ResourceManager.GetString("ResetLinkUsed", resourceCulture);
        /// <summary>Reset link expired. Please request a new one.</summary>
        public static string ResetLinkExpired => ResourceManager.GetString("ResetLinkExpired", resourceCulture);
        /// <summary>If this email is registered, a reset link has been sent.</summary>
        public static string ForgotPasswordSent => ResourceManager.GetString("ForgotPasswordSent", resourceCulture);

        //  Password Validation 

        /// <summary>Passwords do not match.</summary>
        public static string PasswordsMustMatch => ResourceManager.GetString("PasswordsMustMatch", resourceCulture);
        /// <summary>New password must be different from the current password.</summary>
        public static string NewPasswordSameAsOld => ResourceManager.GetString("NewPasswordSameAsOld", resourceCulture);
        /// <summary>Current password is incorrect.</summary>
        public static string CurrentPasswordIncorrect => ResourceManager.GetString("CurrentPasswordIncorrect", resourceCulture);
        /// <summary>Password must contain at least one {0}.</summary>
        public static string PasswordMustContain => ResourceManager.GetString("PasswordMustContain", resourceCulture);

        //  Email Validation 

        /// <summary>Invalid email format.</summary>
        public static string InvalidEmailFormat => ResourceManager.GetString("InvalidEmailFormat", resourceCulture);
        /// <summary>A valid email address is required.</summary>
        public static string InvalidEmail => ResourceManager.GetString("InvalidEmail", resourceCulture);
        /// <summary>No account found with this email address.</summary>
        public static string EmailNotFound => ResourceManager.GetString("EmailNotFound", resourceCulture);
        /// <summary>Email already exists.</summary>
        public static string EmailAlreadyExists => ResourceManager.GetString("EmailAlreadyExists", resourceCulture);
        /// <summary>Email must not exceed 255 characters.</summary>
        public static string EmailMaxLength => ResourceManager.GetString("EmailMaxLength", resourceCulture);

        //  OTP 

        /// <summary>OTP sent successfully.</summary>
        public static string OtpSentSuccessfully => ResourceManager.GetString("OtpSentSuccessfully", resourceCulture);
        /// <summary>OTP verified successfully.</summary>
        public static string OtpVerifiedSuccessfully => ResourceManager.GetString("OtpVerifiedSuccessfully", resourceCulture);
        /// <summary>Invalid or expired OTP.</summary>
        public static string InvalidOrExpiredOtp => ResourceManager.GetString("InvalidOrExpiredOtp", resourceCulture);
        /// <summary>Email and OTP are required.</summary>
        public static string EmailAndOtpRequired => ResourceManager.GetString("EmailAndOtpRequired", resourceCulture);
        /// <summary>OTP must be between 4 and 10 characters.</summary>
        public static string InvalidOtpLength => ResourceManager.GetString("InvalidOtpLength", resourceCulture);
        public static string OtpSecretKeyNotConfigured
        {
            get { return ResourceManager.GetString("OtpSecretKeyNotConfigured", resourceCulture); }
        }

        //  Profile 

        /// <summary>No default image found.</summary>
        public static string DefaultImageNotFound => ResourceManager.GetString("DefaultImageNotFound", resourceCulture);

        //  Address / Geocoding 

        /// <summary>Geocoding successful.</summary>
        public static string GeocodingSuccessful => ResourceManager.GetString("GeocodingSuccessful", resourceCulture);
        /// <summary>Geocoding service unavailable.</summary>
        public static string GeocodingUnavailable => ResourceManager.GetString("GeocodingUnavailable", resourceCulture);
        /// <summary>No address data returned.</summary>
        public static string NoAddressDataReturned => ResourceManager.GetString("NoAddressDataReturned", resourceCulture);
        /// <summary>{0} must be between {1} and {2}.</summary>
        public static string InvalidCoordinate => ResourceManager.GetString("InvalidCoordinate", resourceCulture);
        /// <summary>Mobile number is invalid. Must be 7–15 digits.</summary>
        public static string InvalidMobileNumber => ResourceManager.GetString("InvalidMobileNumber", resourceCulture);
        /// <summary>Mobile number already exists.</summary>
        public static string MobileAlreadyExists => ResourceManager.GetString("MobileAlreadyExists", resourceCulture);

        //  File / Image 

        /// <summary>{0} size exceeds {1}MB limit.</summary>
        public static string FileSizeExceeds => ResourceManager.GetString("FileSizeExceeds", resourceCulture);
        /// <summary>File type not allowed.</summary>
        public static string FileTypeNotAllowed => ResourceManager.GetString("FileTypeNotAllowed", resourceCulture);
        /// <summary>File is required.</summary>
        public static string FileRequired => ResourceManager.GetString("FileRequired", resourceCulture);

        //  Configuration 

        /// <summary>{0} is not configured.</summary>
        public static string NotConfigured => ResourceManager.GetString("NotConfigured", resourceCulture);

        //  Field / Entity Name Labels 

        public static string Admin => ResourceManager.GetString("Admin", resourceCulture);
        public static string User => ResourceManager.GetString("User", resourceCulture);
        public static string UserStatus => ResourceManager.GetString("UserStatus", resourceCulture);
        public static string Contact => ResourceManager.GetString("Contact", resourceCulture);
        public static string Category => ResourceManager.GetString("Category", resourceCulture);
        public static string SubCategory => ResourceManager.GetString("SubCategory", resourceCulture);
        public static string ServiceType => ResourceManager.GetString("ServiceType", resourceCulture);
        public static string Services => ResourceManager.GetString("Services", resourceCulture);
        public static string ServiceName => ResourceManager.GetString("ServiceName", resourceCulture);
        public static string ServiceId => ResourceManager.GetString("ServiceId", resourceCulture);
        public static string ServicePartner => ResourceManager.GetString("ServicePartner", resourceCulture);
        public static string Offer => ResourceManager.GetString("Offer", resourceCulture);
        public static string Commission => ResourceManager.GetString("Commission", resourceCulture);
        public static string Duration => ResourceManager.GetString("Duration", resourceCulture);
        public static string Price => ResourceManager.GetString("Price", resourceCulture);
        public static string CouponCode => ResourceManager.GetString("CouponCode", resourceCulture);
        public static string Description => ResourceManager.GetString("Description", resourceCulture);
        public static string Email => ResourceManager.GetString("Email", resourceCulture);
        public static string EmailId => ResourceManager.GetString("EmailId", resourceCulture);
        public static string Password => ResourceManager.GetString("Password", resourceCulture);
        public static string ConfirmPassword => ResourceManager.GetString("ConfirmPassword", resourceCulture);
        public static string Token => ResourceManager.GetString("Token", resourceCulture);
        public static string RefreshToken => ResourceManager.GetString("RefreshToken", resourceCulture);
        public static string Otp => ResourceManager.GetString("Otp", resourceCulture);
        public static string MobileNumber => ResourceManager.GetString("MobileNumber", resourceCulture);
        public static string MobileMaxLength => ResourceManager.GetString("MobileMaxLength", resourceCulture);
        public static string Address => ResourceManager.GetString("Address", resourceCulture);
        public static string Addresses => ResourceManager.GetString("Addresses", resourceCulture);
        public static string HouseFlatNumber => ResourceManager.GetString("HouseFlatNumber", resourceCulture);
        public static string Language => ResourceManager.GetString("Language", resourceCulture);
        public static string FullName => ResourceManager.GetString("FullName", resourceCulture);
        public static string DateOfBirth => ResourceManager.GetString("DateOfBirth", resourceCulture);
        public static string ApplyingFor => ResourceManager.GetString("ApplyingFor", resourceCulture);
        public static string PermanentAddress => ResourceManager.GetString("PermanentAddress", resourceCulture);
        public static string ResidentialAddress => ResourceManager.GetString("ResidentialAddress", resourceCulture);
        public static string Education => ResourceManager.GetString("Education", resourceCulture);
        public static string Skills => ResourceManager.GetString("Skills", resourceCulture);
        public static string ServicesOffered => ResourceManager.GetString("ServicesOffered", resourceCulture);
        public static string Attachments => ResourceManager.GetString("Attachments", resourceCulture);
        public static string SchoolCollege => ResourceManager.GetString("SchoolCollege", resourceCulture);
        public static string SchoolCollegeMaxLength => ResourceManager.GetString("SchoolCollegeMaxLength", resourceCulture);
        public static string CompanyName => ResourceManager.GetString("CompanyName", resourceCulture);
        public static string CompanyNameMaxLength => ResourceManager.GetString("CompanyNameMaxLength", resourceCulture);
        public static string Role => ResourceManager.GetString("Role", resourceCulture);
        public static string RoleMaxLength => ResourceManager.GetString("RoleMaxLength", resourceCulture);
        public static string FromDate => ResourceManager.GetString("FromDate", resourceCulture);
        public static string Proficiency => ResourceManager.GetString("Proficiency", resourceCulture);
        public static string FileUrl => ResourceManager.GetString("FileUrl", resourceCulture);
        public static string FileName => ResourceManager.GetString("FileName", resourceCulture);
        public static string InvalidPassingYear => ResourceManager.GetString("InvalidPassingYear", resourceCulture);
        public static string PageNumber => ResourceManager.GetString("PageNumber", resourceCulture);
        public static string PageSize => ResourceManager.GetString("PageSize", resourceCulture);

        // New label keys
        public static string Profile => ResourceManager.GetString("Profile", resourceCulture);
        public static string ProfileImage => ResourceManager.GetString("ProfileImage", resourceCulture);
        public static string Latitude => ResourceManager.GetString("Latitude", resourceCulture);
        public static string Longitude => ResourceManager.GetString("Longitude", resourceCulture);
        public static string Image => ResourceManager.GetString("Image", resourceCulture);
        public static string File => ResourceManager.GetString("File", resourceCulture);
        public static string OtpSecretKey => ResourceManager.GetString("OtpSecretKey", resourceCulture);
        public static string JwtKey => ResourceManager.GetString("JwtKey", resourceCulture);
        public static string JwtIssuer => ResourceManager.GetString("JwtIssuer", resourceCulture);
        public static string JwtAudience => ResourceManager.GetString("JwtAudience", resourceCulture);
        public static string SmtpEmail => ResourceManager.GetString("SmtpEmail", resourceCulture);
        public static string UppercaseLetter => ResourceManager.GetString("UppercaseLetter", resourceCulture);
        public static string LowercaseLetter => ResourceManager.GetString("LowercaseLetter", resourceCulture);
        public static string Digit => ResourceManager.GetString("Digit", resourceCulture);
        public static string SpecialCharacter => ResourceManager.GetString("SpecialCharacter", resourceCulture);
        public static string PasswordResetSuccess => ResourceManager.GetString("PasswordResetSuccessfully", resourceCulture);
        public static string Unavailable => ResourceManager.GetString("Unavailable", resourceCulture);
        public static string BookingDatePast => ResourceManager.GetString("BookingDatePast", resourceCulture);
        public static string BookingTimeFormat => ResourceManager.GetString("BookingTimeFormat", resourceCulture);
        public static string SlotUnavailable => ResourceManager.GetString("SlotUnavailable", resourceCulture);
        public static string AddressNotBelongsToUser => ResourceManager.GetString("AddressNotBelongsToUser", resourceCulture);
        public static string PaymentMethodInvalid => ResourceManager.GetString("PaymentMethodInvalid", resourceCulture);
        public static string Booking => ResourceManager.GetString("Booking", resourceCulture);
        public static string Transaction => ResourceManager.GetString("Transaction", resourceCulture);

        public static string BookingTime => ResourceManager.GetString("BookingTime", resourceCulture);
        public static string CouponAlreadyUsed => ResourceManager.GetString("CouponAlreadyUsed", resourceCulture);
        public static string CouponAppliedSuccessfully => ResourceManager.GetString("CouponAppliedSuccessfully", resourceCulture);
        public static string CouponUsageLimitReached => ResourceManager.GetString("CouponUsageLimitReached", resourceCulture);
        public static string DuplicateBookingSlot => ResourceManager.GetString("DuplicateBookingSlot", resourceCulture);
        public static string ServiceDurationNotConfigured => ResourceManager.GetString("ServiceDurationNotConfigured", resourceCulture);
        public static string SlotAvailable => ResourceManager.GetString("SlotAvailable", resourceCulture);
        public static string SlotNotAvailable => ResourceManager.GetString("SlotNotAvailable", resourceCulture);
        public static string BookingCompletionServiceStarted => ResourceManager.GetString("BookingCompletionServiceStarted", resourceCulture);
        public static string BookingCompletionServiceStopped => ResourceManager.GetString("BookingCompletionServiceStopped", resourceCulture);
        public static string BookingCompletionServiceCompleted => ResourceManager.GetString("BookingCompletionServiceCompleted", resourceCulture);
        public static string BookingCompletionServiceError => ResourceManager.GetString("BookingCompletionServiceError", resourceCulture);
        public static string SubmittedAt => ResourceManager.GetString("SubmittedAt", resourceCulture);
        public static string InvalidDate => ResourceManager.GetString("InvalidDate", resourceCulture);
        public static string UserName => ResourceManager.GetString("UserName", resourceCulture);
        public static string FirstName => ResourceManager.GetString("FirstName", resourceCulture);
        public static string SupportTicket => ResourceManager.GetString("SupportTicket", resourceCulture);
        public static string InvalidValue => ResourceManager.GetString("InvalidValue", resourceCulture);
        public static string PaymentNotCompleted => ResourceManager.GetString("PaymentNotCompleted", resourceCulture);
        public static string PaymentAlreadyUsed => ResourceManager.GetString("PaymentAlreadyUsed", resourceCulture);
        public static string CardPaymentUseIntent => ResourceManager.GetString("CardPaymentUseIntent", resourceCulture);
        public static string UnauthorizedPasswordChange => ResourceManager.GetString("UnauthorizedPasswordChange", resourceCulture);
        public static string NoBookingsFound => ResourceManager.GetString("NoBookingsFound", resourceCulture);
        public static string PartnerNotYetAssigned => ResourceManager.GetString("PartnerNotYetAssigned", resourceCulture);
        public static string ApprovedSuccessfully => ResourceManager.GetString("ApprovedSuccessfully", resourceCulture);
        public static string RejectedSuccessfully => ResourceManager.GetString("RejectedSuccessfully", resourceCulture);
        public static string AlreadyApproved => ResourceManager.GetString("AlreadyApproved", resourceCulture);
        public static string AlreadyRejected => ResourceManager.GetString("AlreadyRejected", resourceCulture);
        public static string ServicePartnerNotVerified => ResourceManager.GetString("ServicePartnerNotVerified", resourceCulture);
        public static string Unauthorized => ResourceManager.GetString("Unauthorized", resourceCulture);
        public static string ActionNotAllowed => ResourceManager.GetString("ActionNotAllowed", resourceCulture);
        public static string Change => ResourceManager.GetString("Change", resourceCulture);
        public static string Completed => ResourceManager.GetString("Completed", resourceCulture);
        public static string Cancle => ResourceManager.GetString("Cancle", resourceCulture);
        public static string AlreadyCompleted => ResourceManager.GetString("AlreadyCompleted", resourceCulture);
        public static string InvalidImageType => ResourceManager.GetString("InvalidImageType", resourceCulture);
        public static string AlreadyCancled => ResourceManager.GetString("AlreadyCancled", resourceCulture);
        public static string AccountBlocked => ResourceManager.GetString("AccountBlocked", resourceCulture);
        public static string BookingId => ResourceManager.GetString("BookingId", resourceCulture);
        public static string NewPartnerId => ResourceManager.GetString("NewPartnerId", resourceCulture);
        public static string CancellationReason => ResourceManager.GetString("CancellationReason", resourceCulture);
        public static string BaseURLConfiguration => ResourceManager.GetString("BaseURLConfiguration", resourceCulture);
        public static string BookingsCancelledOnBlock => ResourceManager.GetString("BookingsCancelledOnBlock", resourceCulture);
        public static string BookingsCancelledOnDelete => ResourceManager.GetString("BookingsCancelledOnDelete", resourceCulture);
        public static string ValidLink => ResourceManager.GetString("ValidLink", resourceCulture);
        public static string ServiceUnavailable => ResourceManager.GetString("ServiceUnavailable", resourceCulture);
        public static string CannotDeleteActiveBookings => ResourceManager.GetString("CannotDeleteActiveBookings", resourceCulture);
        public static string CannotDeactivatePartnerSoleAssigned => ResourceManager.GetString("CannotDeactivatePartnerSoleAssigned", resourceCulture);
        public static string CannotDeactivatePartnerChangeExpert => ResourceManager.GetString("CannotDeactivatePartnerChangeExpert", resourceCulture);
        public static string CannotDeletePartnerSoleAssigned => ResourceManager.GetString("CannotDeletePartnerSoleAssigned", resourceCulture);
        public static string CannotDeletePartnerChangeExpert => ResourceManager.GetString("CannotDeletePartnerChangeExpert", resourceCulture);
        public static string AccountDeleted => ResourceManager.GetString("AccountDeleted", resourceCulture);
    }
}